#!/usr/bin/env bash

CXX_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "\.([chi](pp|xx)|(cc|hh|ii)|[CHI])$")

# if not working, run $ sudo apt install clang-format-x
/usr/bin/clang-format-10 -i -style=file ${CXX_CHANGED_FILES}
git add ${CXX_CHANGED_FILES}
