name: cppcheck

on:
  pull_request:
    paths: ["**/*.cpp", "**/*.hpp", "**/*.h", "devenv/cmake/**",
            "CppCheckSuppressions.txt", "devenv/scripts/run-cppcheck.sh"]
  push:
    branches: [main]
    paths: ["**/*.cpp", "**/*.hpp", "**/*.h", "devenv/cmake/**",
            "CppCheckSuppressions.txt", "devenv/scripts/run-cppcheck.sh"]
  workflow_dispatch:

concurrency:
  group: cppcheck-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cppcheck:
    uses: devmarkusb/devenv/.github/workflows/cppcheck.yml@main
    secrets:
      checkout_token: ${{ secrets.SUBMODULES_PAT }}
